sudo: required

services:
  - docker

env:
  - DOCKER_BIND_LOCALHOST=true

language: go

go:
  - 1.2
  - 1.3
  - 1.4
  - 1.5
  - tip

matrix:
  allow_failures:
    - go: tip
    - go: 1.2
    - go: 1.3

install:
  - go get golang.org/x/tools/cmd/vet
  - go get github.com/axw/gocov/gocov
  - go get github.com/mattn/goveralls
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/golang/lint/golint
  - go get -t ./...

script:
  - go vet -x ./...
  - ./coverage --coveralls

